Fix typos
OpenOrienteering/mapper pull request #1862
Opened 2021-01-29 20:04 UTC by luzpaz

2021-01-30 08:09 UTC, dg0yt requested changes
Thank you very much.

Can you drop the osmconf-related commit, or shall I cherry-pick?

2021-01-30 08:09 UTC, dg0yt commented on src/gdal/mapper-osmconf.ini
> +insignificant=created_by,converted_by,source,time,ele,attribution
I'm sorry, but this GDAL syntax:
https://github.com/OSGeo/gdal/blob/93395860dd62e3850ed31b4c77c51a93fe2919c8/gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp#L3613-L3614

2021-02-23 17:53 UTC, dg0yt commented on src/gdal/mapper-osmconf.ini
> +insignificant=created_by,converted_by,source,time,ele,attribution
FTR, osmconf.ini is ignored in our configuration, for this particular reason.
https://github.com/OpenOrienteering/mapper/blob/master/codespell.sh

2021-02-23 19:53 UTC, luzpaz commented
commit reverted, PR squashed and rebased

2021-02-23 23:09 UTC, dg0yt approved these changes
Thanks.

2021-02-23 23:10 UTC, merged