MeasureWidget: Warn about min size in combined symbols
OpenOrienteering/mapper pull request #2084
Opened 2022-08-22 10:04 UTC by lpechacek

This enhancement is especially useful when working with @mlerjen's "halo" symbol set (mentioned multiple times, e.g. in #1004). Please consider merging.

2022-08-22 10:39 UTC, lpechacek commented
> @mlerjen's "halo" symbol set (mentioned multiple times, e.g. in #1004)

I've just realized that it's actually the symbol set contributed in #2032.

2022-08-23 19:21 UTC, dl3sdo requested changes
Libor, thank you for considering combined area symbols. Your commit works fine except in one case: if a new symbol part is just added to the combined symbol  without specifying its type, Mapper will crash due to dereferencing a nullptr. Adding an additional check solves this issue:
`
if (part)
{
	if (part->getType() == Symbol::Area)
	{
		auto symbol_min_area = 0.001 * part->asArea()->getMinimumArea();
		if (symbol_min_area < minimum_area)
			minimum_area = symbol_min_area;
	}
	else if (part->getType() == Symbol::Combined)
	{
		to_be_examined.push(part->asCombined());
	}
}
`
See https://github.com/dl3sdo/mapper/commit/c1b9ed828e863fc66ece0e73e633eb88530efbe5

2022-09-10 17:36 UTC, lpechacek commented
> Libor, thank you for considering combined area symbols. Your commit works fine except in one case: if a new symbol part is just added to the combined symbol without specifying its type, Mapper will crash due to dereferencing a nullptr. Adding an additional check solves this issue: `if (part) { if (part->getType() == Symbol::Area) ........ }` 

Thanks, Matthias, for testing the commit and the fix! I agree with the approach, however, I'd avoid the additional indentation level induced by `if (part) ...` but rather skip the part in the loop with a `continue`. Otherwise, I agree with all the changes and I've merged them into my commit.

2022-09-10 20:09 UTC, dl3sdo approved these changes

2025-01-04 18:36 UTC, closed without merging