Warn on spot color deletion
OpenOrienteering/mapper pull request #2222
Opened 2024-04-13 13:02 UTC by dg0yt

Modification of GH-2209:

- Move color counting to Map. Use algorithms.
- Don't use more than `overprinting_simulation_act ` in `MapEditorController::spotColorPresenceChanged`.
- Show the color name in the spot color removal message. Feels more comfortable when confirming.

2024-04-15 19:31 UTC, dl3sdo requested changes

2024-04-15 19:31 UTC, dl3sdo commented on src/gui/widgets/color_list_widget.cpp
> +			                            color_in_use).arg(color_to_be_removed->getName()),
color_in_use).arg(color_to_be_removed->getSpotColorName()),

2024-04-15 19:31 UTC, dl3sdo commented on src/gui/map/map_editor.cpp
> +			if(overprinting_simulation_act->isChecked())
if (overprinting_simulation_act->isChecked())

2024-04-15 19:38 UTC, dg0yt commented on src/gui/map/map_editor.cpp
> +			if(overprinting_simulation_act->isChecked())
Oh, I'm struggling with CMake code style ;-)

2024-04-15 19:47 UTC, dg0yt commented
TBH I'm unhappy with possibly two dialogs appearing. I think it could make use of the [detailedText](https://doc.qt.io/qt-5/qmessagebox.html#detailedText-prop). This would give more room for text, or maybe even for listing the symbols and colors (https://github.com/OpenOrienteering/mapper/issues/2122).

2024-06-13 09:11 UTC, dl3sdo approved these changes

2024-06-13 09:15 UTC, dl3sdo commented on src/core/map.h
> +	 * Applies a const operation on all colors which match a particular condition.
* Applies a const operation on all symbols which match a particular condition.

2024-06-13 09:17 UTC, dl3sdo requested changes

2024-06-13 09:17 UTC, dl3sdo commented on src/core/map.h
> +	 * Applies a const operation on all colors.
Applies a const operation on all colors.

2024-06-13 09:17 UTC, dl3sdo commented on src/core/map.h
> +	 * Applies a const operation on all colors which match a particular condition.
Applies a const operation on all symbols which match a particular condition.

2024-06-13 12:23 UTC, dg0yt commented on src/core/map.h
> +	 * Applies a const operation on all colors which match a particular condition.
```suggestion
	 * Applies a const operation on all symbols which match a particular condition.
```

2024-06-13 12:23 UTC, dg0yt commented on src/core/map.h
> +	 * Applies a const operation on all colors.
```suggestion
	 * Applies a const operation on all symbols.
```

2024-06-13 12:44 UTC, dl3sdo approved these changes

2024-06-13 18:08 UTC, merged