MeasureWidget: Show warning icon for small objects
OpenOrienteering/mapper pull request #2252
Opened 2024-06-27 23:08 UTC by lpechacek

This change enhances visibility of the small object warning in the measure tool. The use case is to shrink the measure tool window to a minimum size so that only the top line is visible and keep it in the view field during drawing. New sub-size object will trigger the colored warning icon, giving the user opportunity to fix the legibility issue on the go.

Idea contributed by @ollesmaps.

2024-06-28 10:16 UTC, dl3sdo requested changes
Please add `#include <QString>` to .h file since you added `QString warning_icon;`
Proposal: in .h file change to `Copyright 2015, 2024 Kai Pastor`
and add `Copyright 2024 Libor Pecháček` to .cpp file

2024-06-28 10:23 UTC, dl3sdo commented
@lpechacek: thank you Libor for this PR. I successfully tested it:
![MeasureWarningIcon](https://github.com/OpenOrienteering/mapper/assets/14225666/8ea9083b-14c2-45f4-b2ce-8dbf03afd165)

2024-06-28 15:21 UTC, lpechacek commented
> Please add `#include <QString>` to .h file since you added `QString warning_icon;`

Done.

> Proposal: in .h file change to `Copyright 2015, 2024 Kai Pastor` and add `Copyright 2024 Libor Pecháček` to .cpp file

Updated the line with Kai's name as it's now common in OO. I'm not adding my own line for such a triviality though. Although the usability impact of the change is high, the coding effort is not worth a mention.

2024-06-28 16:05 UTC, dl3sdo approved these changes

2024-06-29 04:55 UTC, merged

2024-06-29 04:55 UTC, dg0yt commented
Thanks.